name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties


jobs:
  prebuild-job:
    name: Prebuild Job
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-workflow.yml@main
    with:
      runsOn: ${{ inputs.runsOn }}
  docker-push:
    runs-on: ubuntu-20.04
    needs: [prebuild-job]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "::set-output name=REPOSITORY_NAME::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
      id: meta
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generate .proto description json
      id: proto_json
      run: |
        gradle generateServiceDescriptions
        echo "::set-output name=DESCRIPTION_JSON::$(cat serviceProtoDescription)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR=${{ github.actor }}
        tags: ghcr.io/${{ github.repository }}:${{ needs.prebuild-job.outputs.version }}
        labels: |
          com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ needs.prebuild-job.outputs.version }}
          protobuf-description-base64=${{ steps.proto_json.outputs.DESCRIPTION_JSON }}
  trivy-docker-scan:
    name: Scan Docker image for vulnerabilities
    if: true
    needs: [docker-push, prebuild-job]
    uses: th2-net/.github/.github/workflows/trivy-scan-github.yml@main
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.prebuild-job.outputs.version }}
